# Generated by Django 4.2.3 on 2023-11-17 19:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_owner", models.BooleanField(default=True)),
                ("is_employee", models.BooleanField(default=False)),
                ("user_phone", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now=True)),
                ("pref_clients_per_page", models.PositiveSmallIntegerField(default=10)),
                ("pref_orders_per_page", models.PositiveSmallIntegerField(default=2)),
                (
                    "pref_employees_per_page",
                    models.PositiveSmallIntegerField(default=10),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_already_exists", models.BooleanField(default=False)),
                (
                    "client_first_name",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "client_last_name",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "client_check_mobile_phone",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("deleted_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_subscription_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("company_can_contact", models.BooleanField(default=False)),
                ("company_can_email", models.BooleanField(default=False)),
                ("company_address_lines", models.TextField(max_length=200)),
                ("company_city", models.CharField(max_length=50)),
                ("company_state", models.CharField(max_length=50)),
                ("company_zip_code", models.CharField(max_length=50)),
                ("company_country", models.CharField(max_length=50)),
                ("first_sign_up_date", models.DateTimeField(auto_now_add=True)),
                ("last_sign_up_date", models.DateTimeField(auto_now_add=True)),
                ("first_subscription_date", models.DateTimeField(auto_now_add=True)),
                ("last_subscription_date", models.DateTimeField(auto_now_add=True)),
                ("first_cancelation_date", models.DateTimeField(auto_now_add=True)),
                ("last_cancelation_date", models.DateTimeField(auto_now_add=True)),
                ("deleted_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Standart", "Standart"),
                            ("Premium", "Premium"),
                        ],
                        max_length=30,
                    ),
                ),
                ("plan_frequency", models.CharField(max_length=50)),
                ("plan_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "plan_currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EUR", "EUR"), ("GBP", "GBP")],
                        max_length=10,
                    ),
                ),
                ("plan_description", models.TextField(max_length=200)),
                (
                    "plan_trial_period",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.company",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "work_order_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "work_order_due_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "work_order_currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EUR", "EUR"), ("GBP", "GBP")],
                        max_length=10,
                    ),
                ),
                (
                    "quoted_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "quoted_currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EUR", "EUR"), ("GBP", "GBP")],
                        max_length=10,
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "work_order_type",
                    models.CharField(
                        choices=[
                            ("Sell", "Sell"),
                            ("Repair", "Repair"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "work_order_status",
                    models.CharField(
                        choices=[
                            ("Cancelled", "Cancelled"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="In Progress",
                        max_length=30,
                    ),
                ),
                (
                    "order_photo",
                    models.ImageField(blank=True, null=True, upload_to="order_photos/"),
                ),
                ("deleted_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_flag", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.company",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="company_current_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.plan",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.company",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="BillingLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("billing_date", models.DateTimeField(auto_now_add=True)),
                (
                    "billing_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "billing_status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Unpaid", "Unpaid"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("billing_period_start_date", models.DateTimeField(auto_now_add=True)),
                ("billing_period_end_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.company",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.plan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.company",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
