# Generated by Django 4.2.3 on 2023-07-27 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_log',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company'),
        ),
        migrations.AddField(
            model_name='user_action',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='quoted_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000000),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_order_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000000),
        ),
    ]
