# Generated by Django 4.2.3 on 2023-07-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_billing_log_company_user_action_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='work_order_details',
        ),
        migrations.AlterField(
            model_name='billing_log',
            name='billing_amount',
            field=models.DecimalField(decimal_places=2, max_digits=100000000000),
        ),
        migrations.AlterField(
            model_name='billing_log',
            name='billing_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Canceled', 'Canceled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='quoted_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_order_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_order_status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_order_type',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Repair', 'Repair'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=30),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, max_digits=100000000000),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_trial_period',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
