# Generated by Django 4.2.3 on 2023-07-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_company_owner_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_activity_log',
            name='client',
        ),
        migrations.RemoveField(
            model_name='user_activity_log',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_activity_log',
            name='user_action',
        ),
        migrations.RemoveField(
            model_name='user_activity_log',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_features',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='User_Action',
        ),
        migrations.DeleteModel(
            name='User_Activity_Log',
        ),
        migrations.DeleteModel(
            name='User_Role',
        ),
    ]
