# Generated by Django 4.2.3 on 2023-07-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_user_activity_log_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000000),
        ),
    ]
