# Generated by Django 4.2.3 on 2023-07-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_order_security_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_check_mobile_phone',
            field=models.BooleanField(default=False),
        ),
    ]
