# Generated by Django 4.2.3 on 2023-07-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_client_client_check_mobile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='work_order_price',
            new_name='estimated_cost',
        ),
    ]
