# Generated by Django 4.2.3 on 2023-07-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_rename_work_order_price_order_estimated_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='new_client',
            field=models.BooleanField(default=False),
        ),
    ]
