# Generated by Django 4.2.3 on 2023-07-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_client_new_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='new_client',
            new_name='client_already_exists',
        ),
    ]
