# Generated by Django 4.2.3 on 2023-08-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_rename_new_client_client_client_already_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='work_order_due_date',
            field=models.DateTimeField(max_length=50),
        ),
    ]
