# Generated by Django 4.2.3 on 2023-08-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_order_work_order_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000000),
        ),
    ]
