# Generated by Django 4.2.3 on 2023-08-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_client_total_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role_name', models.CharField(choices=[('Owner', 'Owner'), ('Manager', 'Manager'), ('Employee', 'Employee')], max_length=30)),
                ('user_role_description', models.TextField(max_length=200)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
