# Generated by Django 4.2.3 on 2023-08-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_role',
            name='user_role_name',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Employee', 'Employee')], max_length=30),
        ),
    ]
