# Generated by Django 4.2.3 on 2023-08-15 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_user_role_user_role_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Billing_Log',
            new_name='BillingLog',
        ),
        migrations.RenameModel(
            old_name='User_Role',
            new_name='UserRole',
        ),
    ]
