# Generated by Django 4.2.3 on 2023-08-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_user_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.AddField(
            model_name='user',
            name='user_role_name',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Employee', 'Employee')], default='Employee', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
