# Generated by Django 4.2.3 on 2023-08-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_remove_user_user_role_name_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Owner'), (2, 'MasterAdmin'), (3, 'Employee')], null=True),
        ),
    ]
