# Generated by Django 4.2.3 on 2023-08-20 16:37

import customers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, default=customers.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, default=customers.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company'),
        ),
    ]
