# Generated by Django 4.2.3 on 2023-08-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_alter_client_company_alter_order_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CompanyOwner'), (2, 'CompanyAdmin'), (3, 'Employee')], null=True),
        ),
    ]
