# Generated by Django 4.2.3 on 2023-08-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='user_company',
        ),
    ]
