# Generated by Django 4.2.3 on 2023-08-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_rename_company_user_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_company',
            new_name='company',
        ),
    ]
