# Generated by Django 4.2.3 on 2023-08-28 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0026_rename_user_company_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_subscription_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Cancelled', 'Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_order_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=30),
        ),
    ]
