# Generated by Django 4.2.3 on 2023-08-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0027_client_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='work_order_due_date',
            field=models.DateTimeField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
