# Generated by Django 4.2.3 on 2023-08-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0028_alter_order_work_order_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinglog',
            name='billing_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Cancelled', 'Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'is_owner'), (2, 'is_admin'), (3, 'is_employee')], null=True),
        ),
    ]
