# Generated by Django 4.2.3 on 2023-08-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_alter_billinglog_billing_status_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pref_clients_per_page',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='pref_orders_per_page',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
