# Generated by Django 4.2.3 on 2023-08-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0030_user_pref_clients_per_page_user_pref_orders_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pref_orders_per_page',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
