# Generated by Django 4.2.3 on 2023-08-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0031_alter_user_pref_orders_per_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=True),
        ),
    ]
