# Generated by Django 4.2.3 on 2023-08-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0034_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pref_employees_per_page',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
