# Generated by Django 4.2.3 on 2023-08-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0035_user_pref_employees_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standart', 'Standart'), ('Premium', 'Premium')], max_length=30),
        ),
    ]
