# Generated by Django 4.2.3 on 2023-08-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0037_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_flag',
        ),
    ]
