# Generated by Django 4.2.3 on 2023-08-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0038_remove_user_deleted_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='work_order_description',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
