# Generated by Django 4.2.3 on 2023-09-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0039_alter_order_work_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
