# Generated by Django 4.2.3 on 2023-09-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0040_alter_client_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
