# Generated by Django 4.2.3 on 2023-09-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0042_alter_client_client_check_mobile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos'),
        ),
    ]
