# Generated by Django 4.2.3 on 2023-09-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0043_order_order_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/'),
        ),
    ]
