# Generated by Django 4.2.3 on 2023-10-04 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0044_alter_order_order_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='work_order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_order_due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
