# Generated by Django 4.2.3 on 2023-10-04 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0045_alter_order_work_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='work_order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_order_due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
