# Generated by Django 4.2.3 on 2023-10-07 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0046_alter_order_work_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_phone',
        ),
    ]
