# Generated by Django 4.2.3 on 2023-10-07 04:00

from django.db import migrations

def add_default_plan(apps, schema_editor):
    Plan = apps.get_model('customers', 'Plan')
    Plan.objects.create(
        plan_name='Basic',
        plan_frequency='Monthly',
        plan_price=9.99,
        plan_currency='USD',
        plan_description='Basic plan description',
        plan_trial_period='No'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0047_remove_company_company_email_and_more'),
    ]

    operations = [
        migrations.RunPython(add_default_plan),
    ]
