# Generated by Django 4.2.3 on 2023-10-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0048_add_default_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='work_order_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=30),
        ),
    ]
