# Generated by Django 4.2.3 on 2023-10-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0049_alter_order_work_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_country',
        ),
    ]
