# Generated by Django 4.2.3 on 2023-10-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0050_remove_company_company_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='work_order_description',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
