# Generated by Django 4.2.3 on 2023-10-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0051_remove_order_work_order_description_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note_id',
            field=models.IntegerField(default=0),
        ),
    ]
