# Generated by Django 4.2.3 on 2023-10-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0053_alter_order_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note_id',
        ),
    ]
