# Generated by Django 4.2.3 on 2023-10-15 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0056_note_created_at_note_deleted_flag_note_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company'),
        ),
    ]
